### ISSUE TITLE
Multi files support

### ISSUE THREAD

**Issue by karniv00l** [patmood/pocketbase-typegen#3]
Hi, great project!

I've noticed that types generated for the fields that can handle more than one file, are just `string` instead of `string[]`

**Comment by patmood** [comment]
Hey thanks for reporting! I just published an update to fix this. Let me know if you find any more issues. I haven't gone through all the different possible options for fields yet.

**Comment by karniv00l** [comment]
Hey, thanks for looking into it, unfortunately looks like you forgot to build the package and the new code isn't there. 

I've opened a small [PR](https://github.com/patmood/pocketbase-typegen/pull/4) that may help a little bit with publishing, however I would recommend automatic the process, here's an example: https://github.com/karniv00l/mlg-converter/blob/master/.github/workflows/npm-publish.yml

**Comment by patmood** [comment]
🤦 sorry about that. I've re-published and will automate it soon.
